[package]
name = "todo"
version = "0.1.0"
description = "Command-line TO-DO application"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
repository = "https://github.com/kobby-pentangeli/todo"
readme = "README.md"
edition = "2018"

[dependencies]
serde_json = "1.0.61"
